docs/changelog.md
Je suis parti sur une 0.2.0 car il y a beaucoup de nouveautés.
Je pense qu'on pourrait même partir sur une 1.0.0.
J'ai noté aussi quelques points à vérifier ou clarifier avant la release.
=> Changelog 0.2.0

README.rst
fix "widget_type"="number" ("int" ne fonctionne pas)
=> readme widget_type int --> number

docs/changelog.rst
cf. https://github.com/PnX-SI/gn_module_monitoring/issues/119#issuecomment-953072053
=> Ajout information sur la mise à jour des modulesjs

contrib/POPReptile/nomenclature.json
Rajout des nomenclatures manquantes PLUVIOSITE, NOMBRE_ESTIME, VENT, ENSOLEILLEMENT (cf. https://github.com/PnX-SI/gn_module_monitoring/issues/129#issuecomment-971666104)
=> Rajout des nomenclatures manquantes

frontend/app/components/monitoring-object/monitoring-object.component.css, frontend/app/components/monitoring-object/monitoring-object.component.ts
Corrige la hauteur aléatoire du container principal
=> fix container heigth

backend/monitoring/definitions.py, backend/monitoring/models.py, frontend/app/components/monitoring-map/monitoring-map.component.html, frontend/app/components/monitoring-map/monitoring-map.component.ts, frontend/app/components/monitoring-object/monitoring-object.component.html, frontend/app/components/monitoring-object/monitoring-object.component.ts
- Calcul de la géometrie des groupe de site côté backend (prend l'enveloppe convexe des sites du groupe : https://postgis.net/docs/ST_ConvexHull.html)
- Zoom sur les layers au clic sur la liste
=> Group site geometry

frontend/app/components/monitoring-form/monitoring-form.component.ts
Ticket : https://github.com/PnX-SI/gn_module_monitoring/issues/152
=> redirect to parent 

docs/sous_module.rst, frontend/app/components/modules/modules.component.css, frontend/app/components/modules/modules.component.html
Proposition de mise en forme des cartes de la page d'accueil du module (fix #214)
=> fix for #214

backend/gn_module_monitoring/monitoring/objects.py
=> fix error on site create from module

backend/gn_module_monitoring/monitoring/admin.py, backend/gn_module_monitoring/monitoring/schemas.py, backend/gn_module_monitoring/routes/site.py, backend/gn_module_monitoring/tests/fixtures/type_site.py, backend/gn_module_monitoring/tests/test_monitoring/test_models/test_bib_type_site.py, backend/gn_module_monitoring/tests/test_monitoring/test_schemas/test_bib_site_type_schema.py, backend/gn_module_monitoring/utils/routes.py
Point tables models to their new location
=> fix: use table models migrated in geonature core

backend/gn_module_monitoring/monitoring/queries.py, backend/gn_module_monitoring/routes/sites_groups.py, frontend/app/components/monitoring-datatable-g/monitoring-datatable-g.component.html, frontend/app/components/monitoring-datatable-g/monitoring-datatable-g.component.ts, frontend/app/components/monitoring-sites/monitoring-sites.component.ts, frontend/app/components/monitoring-sitesgroups/monitoring-sitesgroups.component.html, frontend/app/components/monitoring-sitesgroups/monitoring-sitesgroups.component.ts, frontend/app/services/geojson.service.ts
=> Ajout interaction carte/liste

backend/gn_module_monitoring/monitoring/queries.py, backend/gn_module_monitoring/tests/fixtures/generic.py, backend/gn_module_monitoring/tests/fixtures/site.py, backend/gn_module_monitoring/tests/test_routes/test_site.py
=> Corrections filtre des sites via id_inventor

frontend/app/class/monitoring-object-base.ts, frontend/app/class/monitoring-object.ts, frontend/app/components/monitoring-map/monitoring-map.component.ts, frontend/app/services/api-geom.service.ts, frontend/app/services/geojson.service.ts
=> [DEV-SUIVI-EOLIEN] style(front): apply prettier

frontend/app/class/monitoring-object.ts, frontend/app/components/monitoring-form/monitoring-form.component.ts, frontend/app/services/form.service.ts
Use only formValue created in formService
Reviewed-by: andriacap
=> [DEV-SUIIVI-EOLIEN] refact: remove duplicate formValue

backend/gn_module_monitoring/command/utils.py, backend/gn_module_monitoring/tests/test_commands/test_commands.py, contrib/test/nomenclature.json
Permettre la mise à jour des items de nomenclature
=> Update nomenclature with install and add_module_nomenclature cmd

backend/gn_module_monitoring/config/utils.py, docs/changelog.md
Bug du composant groupe de site lors de l'édition d'un site
=> Correction config widget type de site

backend/gn_module_monitoring/monitoring/models.py
Add all columns inside table object declaration.
Prevent site groups deletion from site deletion + optimize some queries
=> fix(sites): correct model for sites and group sites

backend/gn_module_monitoring/config/generic/config.json, backend/gn_module_monitoring/config/generic/module.json, backend/gn_module_monitoring/config/generic/sites_group.json, backend/gn_module_monitoring/config/repositories.py, backend/gn_module_monitoring/migrations/f24adb481f54_remove_id_module_from_sites_groups.py, backend/gn_module_monitoring/monitoring/geom.py, backend/gn_module_monitoring/monitoring/models.py, backend/gn_module_monitoring/monitoring/queries.py, backend/gn_module_monitoring/monitoring/schemas.py, backend/gn_module_monitoring/routes/data_utils.py, backend/gn_module_monitoring/routes/sites_groups.py, frontend/app/class/monitoring-object.ts, frontend/app/components/monitoring-datatable/monitoring-datatable.component.ts, frontend/app/components/monitoring-form/monitoring-form.component.ts, frontend/app/components/monitoring-lists/monitoring-lists.component.html, frontend/app/components/monitoring-lists/monitoring-lists.component.ts, frontend/app/components/monitoring-map/monitoring-map.component.ts, frontend/app/components/monitoring-object/monitoring-object.component.html, frontend/app/components/monitoring-object/monitoring-object.component.ts, frontend/app/gnModule.module.ts, frontend/app/services/geojson.service.ts, frontend/app/services/list.service.ts
Ajout d'une relation entre module et groupe de sites.
=> Association groupes de site / modules

frontend/app/components/monitoring-sites-detail/monitoring-sites-detail.component.ts, frontend/app/services/config.service.ts
Affichage des propriétés spécifiques dans le gestionnaire de site en l'absence de display properties dans le type de site
=> Display specific properties

frontend/app/components/draw-form/draw-form.component.ts, frontend/app/components/monitoring-datatable-g/monitoring-datatable-g.component.ts, frontend/app/components/monitoring-datatable/monitoring-datatable.component.ts, frontend/app/components/monitoring-lists/monitoring-lists.component.html, frontend/app/components/monitoring-lists/monitoring-lists.component.ts, frontend/app/components/monitoring-map-list/monitoring-map-list.component.ts, frontend/app/components/monitoring-sites-create/monitoring-sites-create.component.ts, frontend/app/components/monitoring-sites-detail/monitoring-sites-detail.component.html, frontend/app/components/monitoring-sites-detail/monitoring-sites-detail.component.ts, frontend/app/components/monitoring-sitesgroups-create/monitoring-sitesgroups-create.component.ts, frontend/app/components/monitoring-sitesgroups-detail/monitoring-sitesgroups-detail.component.html, frontend/app/components/monitoring-sitesgroups-detail/monitoring-sitesgroups-detail.component.ts, frontend/app/interfaces/object.ts, frontend/app/services/form.service.ts
Utilisation d'un BehaviorSubject spécifique pour savoir si la carte est en mode édition. 
#392
=> Fix edit map mode

frontend/app/class/monitoring-object-base.ts, frontend/app/components/monitoring-datatable/monitoring-datatable.component.html, frontend/app/components/monitoring-datatable/monitoring-datatable.component.ts
Detection si le nom du type d'objet commence ou non par une voyelle. Si oui affichage de nouvel et non pas nouveau.
=> [frontend] Test si nouveau ou nouvel objet

frontend/app/components/modules/modules.component.html
On peut avoir des protocoles installés, mais pas les permissions pour y accéder.
=> Update modules.component.html - Change message
